version: '3'

services:
  web:
    build: ./web
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - my_network
    restart: always

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
