services:
  app:
    build: .
    container_name: express-app
    restart: always
    depends_on:
      - redis
      - postgres
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
